defmodule Twitter.Repo.Migrations.AddLabelToTweet do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tweets) do
      add :label, :text
    end
  end

  def down do
    alter table(:tweets) do
      remove :label
    end
  end
end
